### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#19]
I'm putting some todos here. This isn't the final list, and likely will fall out of date.

- Optimizer mixing checks [#21]
- Docs [#23]
- Sampler
  - [x] Check if can get a perf boost by computing gradients for multiple chains together - [yes see #24 ]
- Reparameterization
  - [x] Manual non-centering syntax [#6 ]
  - [x] Sampler implementation (in progress, see #28)
- Interface
  - [x] Command line interface #42
  - [x] Status for MCMC #42 
- Serialization
  - [x] Save/load fit results (#38)
- Predictions
  - [x] Produce intermediate quantities as outputs (#36)
- Compile errors
  - [x] #32
- Parser/Scanner improvements
  - [x] verbose output #32 
  - [x] operator precedence #40 
  - [ ] ~~ops rewrite~~ - postponed to after 1.0
- Big example model
  - [x] Starting with #41
  - [x] A CCES example would also be good -- maybe port [this](https://bookdown.org/jl5522/MRP-case-studies/introduction-to-mrp.html)

Other things:
- Serializing models themselves
- Multiple input dataframes (instead of only a single dataframe)
- Laplace approximation
- Kalman-like update
- Prior/Posterior predictive stuff
  - Made an rng prototype but decided to not implement it right away, see #37. The interface wasn't so obvious (normally variables are defined by use but since rngs aren't used in the program they're a bit weird)
  - With transformed parameters can do quite a bit
  - It's not clear how to do out of sample prediction stuff yet -- not sure how to write down the problems even, but the simple problem is, fit model to data X, predict on Y -- not ready
  - Check out:
    - Bottom of page 147 (independence of sequence) in [BDA3](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf)
    - "Model checking and the likelihood principle" on page 152
- Leave-stuff-out predictive
- Offset-multiply
  - I don't think this solves anything that we can't already solve with regular transformed parameters.
- Implement cumsum
  - The cumsum would be useful for implementing non-centered time series things (innovation parameterization). I expect a lot of time series models to need this to sample without divergences
  - For this to be useful we need a better way to do groupbys -- the cumsum would need targeted to only certain variables

Other things from Bob's ProbProg talk on Workflow:
- Model Comparison
- Automatic non-centering syntax
- Model averaging/mixing/stacking
- Deploy in production
- Modular components
- Clamping parameters
- [x] Automatic GPU
- Working with distributed teams
- Name and store
  - Model variants
  - Output
- SBC
- Sensitivity

**Comment by bbbales2** [comment]
Inferring factor structure is kinda necessary for rat to be easy to use. It's like, we could ask someone to define a full schema for the dataframes that they pass in but that's so much boilerplate.

In lieu of this we try to infer if multiple columns are the same thing and build factors that cover multiple columns and allow subscript renaming. I think I'm saying this weird, but it's the home_team/away_team thing:

```
score_diff ~ normal(skill[home_team] - skill[away_team]);
skill[team] ~ normal(0, sigma);
```

So it's nice that we do this automatically here.

A more confusing case would be:

```
score_diff ~ normal(skill[home_team] - skill[away_team] + something_else[home_team]);
```

Does `something_else` now also get defined for values of `away_team` that might not be in `home_team` or not?

I think it will be useful to try to address this, but I'm not sure a solution.

R and Pandas and whatnot have factors, but something that bothers me about factors is:
1. They're awkward to define completely
2. It's never actually true that they're defined completely. For instance, factors for dates -- well there's always the future. Even things like US states -- do we count the District of Columbia? Well maybe we make a decision now -- but the future can change this for sure.

This also comes up in brms/rstanarm when it comes to making predictions on unobserved things (for a new state -- do we sample from the prior? Or do we sample from one of the other state parameters we already have?)

Anyway, I wonder if we could have a syntax for annotating factors and details about them such that:
1. The compiler could figure out what everything should be
2. And if there are ambiguities throw an error and provide a template of what the user needs to provide to solve the ambiguity

**Comment by Dashadower** [comment]
> 
> A more confusing case would be:
> 
> ```
> score_diff ~ normal(skill[home_team] - skill[away_team] + something_else[home_team]);
> ```
> 
> Does `something_else` now also get defined for values of `away_team` that might not be in `home_team` or not?

It should only exist for values that are present in the `home_team` column. There's no way to tell whether `home_team` or `away_team` should be the "basis team" and `home_team` is explicitly present within the data.

If we wanted `something_else` to exist for all teams present in `home_team` and `away_team`, we might try:
```
score_diff ~ normal(skill[home_team] - skill[away_team] + something_else[team]);
```
And once the compiler identifies `team` isn't present as a data column, it would be a union of the two team columns? But I don't think this approach should be naively used since this makes typing errors go silent.

Alternatively, we might allow the definition of custom subscripts? So something like 
```
team = home_team | away_team
```
This reminds me of the subscript `union` operator we scrapped.

**Comment by Dashadower** [comment]
Regarding factors, the only reliable and type-agnostic info we have are the subscript orders. So if want option 1 with no additional stuff supplied from the user, we will probably have to make strong assumptions(read as: trust that the user didn't screw up).

**Comment by bbbales2** [comment]
We did it!
