### ISSUE TITLE
City Rat Todo List

### ISSUE THREAD

**Issue by Dashadower** [bbbales2/regressions#72]
## City Rat todo list

- [x] Code generator rewrite  [#69]
  - We're hopefully future proofing ourselves a little with a code-gen cleanup. The code gen is not baked into the AST now.
- [x] A way to specify initial conditions for recursive statements/priors with shifts
   - To support random walks we need a way of conditionally specifying the first one or two elements are different from the others. The simplest way to do this is probably some sort of condition -- be it an `ifelse(cond, case1, case2)` function or a fancier `case1 if cond else case2` statement.
- [x] Docs [#70]
- [x] Multiple input dataframes [https://github.com/bbbales2/regressions/pull/77]
   - [x] Can use multiple dataframes within a rat program
   - [x] Can pass multiple dataframes from rat CLI
   - [x] Docs demonstrate how to use multiple dataframes

## Neat future plans not part of City Rat
- Getting predictions in for City Rat is too big a thing - quite unsure of a design here. I think this is something that we should work out though along with some sort of way to handle cross validation (leave one out, leave future out, etc).
  - There may be convenient interface differences for predicting new parameters and making predictions on more data
  - Given a prediction, how to determine what data is required?
  - Not sure to what extent predictions can be made without rerunning sampler vs. what requires generating new samples

**Comment by bbbales2** [comment]
Hoooray! It is done. I think I'll pin a release just for funsies.
